name: libretro Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/libretro/libretro-super.git
  REPO_BRANCH: master
  PKG_NAME: libretro-super
  LIB_NAMES: ardens fceumm gambatte gpsp handy mednafen_ngp mednafen_pce_fast mednafen_wswan pcsx_rearmed picodrive pokemini retro8 snes9x2005 fbalpha2012
  BIN_DIR: /
  CONFIG_FILE: configs/libretro.config
  DIY_SH: configs/diy.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
  
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y -q --no-install-recommends build-essential make cmake wget autogen autoconf automake -y
        sudo apt-get -y autoremove
        sudo apt-get -y clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/# \(en_US.UTF-8\)/\1/' /etc/locale.gen
        sudo locale-gen --purge --lang en_US.UTF-8
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b --depth 1 $REPO_BRANCH $PKG_NAME
        ln -sf /workdir/$PKG_NAME $GITHUB_WORKSPACE/$PKG_NAME
        cd && wget https://github.com/junfeng142/Demo-project/releases/download/2025.01.21-2345/FunKey-sdk-2.3.0.tar.gz
        cd && tar xvf FunKey-sdk-2.3.0.tar.gz
        sudo mv FunKey-sdk-2.3.0 /opt

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $PKG_NAME/.config
        mv configs/*.patch $PKG_NAME/
        chmod +x $DIY_SH
        cd $PKG_NAME
        $GITHUB_WORKSPACE/$DIY_SH
        git submodule update --init --recursive
        ./libretro-fetch.sh $LIB_NAMES

    - name: Compile the firmware
      id: compile
      run: |
        cd $PKG_NAME
        echo -e "$(nproc) thread compile"
        ./libretro-build.sh $LIB_NAMES
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DEVICE_NAME=$PKG_NAME" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        mv $PKG_NAME/dist/*/*.so $PKG_NAME/_opk/
        cd $PKG_NAME/_opk
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*.so
